[tool.ruff]
line-length = 88
target-version = "py311"

exclude = ['src/d2l_raw']

[tool.ruff.lint]
select = ["E", "W", "F", "I", "B", "UP"]
ignore = ['F401']

# 4. Allow fixing for all enabled rules (when `--fix` is used)
fixable = ["ALL"]
unfixable = []

[tool.ruff.lint.per-file-ignores]

[tool.ruff.lint.isort]

[tool.ruff.lint.pydocstyle]
convention = "google"
